name: "deploy"

on:
  workflow_dispatch:
  push:

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        
      - name: Build project
        run: > 
          set -ex
          && cp -r www public
          && cat www/index.html
          | sed s/SEUNUMERODOTELEFONE/${{ secrets.SEUNUMERODOTELEFONE }}/g
          | sed s/GA_TRACKING_ID/${{ secrets.GA_TRACKING_ID }}/g
          > public/index.html

      - name: Deploy project
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: morais-vet-br
          directory: public
          #gitHubToken: ${{ secrets.GITHUB_TOKEN }}
